# Generated by Django 4.1 on 2024-10-03 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='arl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='base_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.IntegerField(unique=True)),
                ('tipo_id', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI'), ('PPT', 'PPT'), ('PEP', 'PEP'), ('PA', 'PA')], max_length=255)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_riesgo', models.CharField(choices=[('0.522', '0.522'), ('1.044', '1.044'), ('4.35', '4.35'), ('NO APLICA', 'NO APLICA'), ('OTRO', 'OTRO')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_vivienda', models.CharField(choices=[('Propia', 'Propia'), ('Familiar', 'Familiar'), ('Arrendada', 'Arrendada')], max_length=255)),
                ('nivel_educativo', models.CharField(choices=[('BASICA PRIMARIA', 'BASICA PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('BACHILLER', 'BACHILLER'), ('TECNICO', 'TECNICO'), ('TECNOLOGO', 'TECNOLOGO'), ('UNIVERSITARIO/PROFESIONAL', 'UNIVERSITARIO/PROFESIONAL'), ('INGENIERO', 'INGENIERO'), ('ESPECIALISTA', 'ESPECIALISTA'), ('MAGISTER', 'MAGISTER'), ('DOCTORADO', 'DOCTORADO')], max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=255)),
                ('rh', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('ND', 'NO DEFINIDO')], max_length=255)),
                ('estado_civil', models.CharField(choices=[('SOLTERO (A)', 'SOLTERO (A)'), ('CASADO (A)', 'CASADO (A)'), ('VIUDO (A)', 'VIUDO (A)'), ('DIVORCIADO (A)', 'DIVORCIADO (A)'), ('UNION LIBRE', 'UNION LIBRE')], max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('talla_camisa', models.CharField(blank=True, max_length=255, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=255, null=True)),
                ('talla_calzado', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('arl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.arl')),
            ],
        ),
        migrations.CreateModel(
            name='canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('cantidad_aprobada', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.area')),
            ],
            options={
                'unique_together': {('descripcion', 'area')},
            },
        ),
        migrations.CreateModel(
            name='cceco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ccf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='contratos_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_periodo_prueba', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_ingreso', models.CharField(choices=[('A', 'Aprendizaje'), ('T', 'Temporal'), ('V', 'Vinculado')], max_length=255)),
                ('modalidad_ingreso', models.CharField(choices=[('NUEVO INGRESO POR TEMPORAL', 'NUEVO INGRESO POR TEMPORAL'), ('REINGRESO', 'REINGRESO'), ('NUEVO INGRESO DIRECTO', 'NUEVO INGRESO DIRECTO'), ('NUEVO INGRESO DIRECTO (TEMPORAL A DIRECTO)', 'NUEVO INGRESO DIRECTO (TEMPORAL A DIRECTO)')], max_length=255)),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Obra o Labor', 'Obra o Labor'), ('Aprendizaje', 'Aprendizaje')], max_length=255)),
                ('salario_base', models.FloatField()),
                ('auxilio_transporte', models.FloatField(blank=True, null=True)),
                ('base_bonificacion', models.FloatField(blank=True, null=True)),
                ('bonificacion', models.CharField(blank=True, choices=[('0,3', '0,3'), ('1,1', '1,1'), ('1,28', '1,28'), ('2,3', '2,3'), ('2,56', '2,56'), ('3,2', '3,2'), ('3,48', '3,48'), ('3,84', '3,84'), ('5,12', '5,12')], max_length=255, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro_real', models.CharField(blank=True, max_length=255, null=True)),
                ('activo_desde', models.DateField(blank=True, null=True)),
                ('activo_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.area')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.canal')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.cargo')),
                ('cceco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.cceco')),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='empleadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fondo_cesantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fondo_pensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='motivos_retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('codigo_map', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='temporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_auxilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='historico_base_teorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.cargo')),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('dependecia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='empalmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(choices=[('Licencia maternidad', 'Licencia maternidad'), ('Licencia medica', 'Licencia medica'), ('Reemplazo', 'Reemplazo'), ('NA', 'No aplica')], max_length=255)),
                ('contrato_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.contratos_personal')),
                ('quien_ingresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quien_ingresa', to='human_resources.base_personal')),
                ('quien_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quien_sale', to='human_resources.base_personal')),
            ],
        ),
        migrations.CreateModel(
            name='descargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.base_personal')),
            ],
        ),
        migrations.AddField(
            model_name='contratos_personal',
            name='empleador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.empleadores'),
        ),
        migrations.AddField(
            model_name='contratos_personal',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jefe_inmediato', to='human_resources.base_personal'),
        ),
        migrations.AddField(
            model_name='contratos_personal',
            name='motivo_retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.motivos_retiro'),
        ),
        migrations.AddField(
            model_name='contratos_personal',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.sede'),
        ),
        migrations.AddField(
            model_name='contratos_personal',
            name='temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.temporales'),
        ),
        migrations.AddField(
            model_name='contratos_personal',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajador', to='human_resources.base_personal'),
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='cambios_salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('salario_anterior', models.FloatField()),
                ('nuevo_salario', models.FloatField()),
                ('motivo', models.CharField(max_length=255)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.contratos_personal')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.base_personal')),
            ],
        ),
        migrations.AddField(
            model_name='base_personal',
            name='ccf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.ccf'),
        ),
        migrations.AddField(
            model_name='base_personal',
            name='cesantias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.fondo_cesantias'),
        ),
        migrations.AddField(
            model_name='base_personal',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.ciudad'),
        ),
        migrations.AddField(
            model_name='base_personal',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.departamento'),
        ),
        migrations.AddField(
            model_name='base_personal',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.eps'),
        ),
        migrations.AddField(
            model_name='base_personal',
            name='pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.fondo_pensiones'),
        ),
        migrations.CreateModel(
            name='auxilios_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.contratos_personal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.tipos_auxilio')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='estructura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.estructura'),
        ),
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.base_personal'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('descripcion', 'estructura')},
        ),
    ]
