# Generated by Django 4.1 on 2025-02-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_alter_sede_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='codigo_map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
