# Generated by Django 4.1 on 2025-02-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_sede_codigo_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='codigo_sap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
