# Generated by Django 4.1 on 2025-02-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_alter_sede_codigo_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cceco',
            name='codigo_sap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
