# Generated by Django 4.1 on 2025-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_cceco_codigo_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cceco',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
