# Generated by Django 4.1 on 2025-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_alter_cceco_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='criticidad',
            field=models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], default='MEDIA', max_length=255),
        ),
    ]
