# Generated by Django 4.1 on 2025-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_cargo_criticidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_personal',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
