# Generated by Django 4.1 on 2025-03-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_base_personal_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_personal',
            name='fecha_creacion',
        ),
    ]
