# Generated by Django 4.1 on 2025-03-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_remove_base_personal_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos_personal',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.canal'),
        ),
        migrations.AlterField(
            model_name='contratos_personal',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador', to='human_resources.base_personal'),
        ),
    ]
