# Generated by Django 4.1 on 2025-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_alter_contratos_personal_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personal',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('BASICA PRIMARIA', 'BASICA PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('BACHILLER', 'BACHILLER'), ('TECNICO', 'TECNICO'), ('TECNOLOGO', 'TECNOLOGO'), ('UNIVERSITARIO/PROFESIONAL', 'UNIVERSITARIO/PROFESIONAL'), ('INGENIERO', 'INGENIERO'), ('ESPECIALISTA', 'ESPECIALISTA'), ('MAGISTER', 'MAGISTER'), ('DOCTORADO', 'DOCTORADO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contratos_personal',
            name='bonificacion',
            field=models.CharField(blank=True, choices=[('0,3', '0,3'), ('1,1', '1,1'), ('1,28', '1,28'), ('2,3', '2,3'), ('2,56', '2,56'), ('3', '3'), ('3,2', '3,2'), ('3,48', '3,48'), ('3,5', '3,5'), ('3,84', '3,84'), ('4,5', '4,5'), ('5,12', '5,12')], max_length=255, null=True),
        ),
    ]
