# Generated by Django 4.1 on 2025-04-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0012_alter_base_personal_nivel_educativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personal',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO (A)', 'SOLTERO (A)'), ('CASADO (A)', 'CASADO (A)'), ('VIUDO (A)', 'VIUDO (A)'), ('DIVORCIADO (A)', 'DIVORCIADO (A)'), ('UNION LIBRE', 'UNION LIBRE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_personal',
            name='rh',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('ND', 'NO DEFINIDO')], max_length=255, null=True),
        ),
    ]
