# Generated by Django 4.1 on 2025-04-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0013_alter_base_personal_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
