# Generated by Django 4.1 on 2025-04-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0014_alter_base_personal_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personal',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='human_resources.eps'),
        ),
        migrations.AlterField(
            model_name='base_personal',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('Propia', 'Propia'), ('Familiar', 'Familiar'), ('Arrendada', 'Arrendada')], max_length=255, null=True),
        ),
    ]
