# Generated by Django 4.1 on 2025-05-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0015_alter_base_personal_eps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_personal',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
