# Generated by Django 4.1 on 2026-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0016_base_personal_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos_personal',
            name='tipo_posicion',
            field=models.CharField(blank=True, choices=[('HC', 'HC'), ('HC PLUS', 'HC PLUS'), ('ESTRATEGIA ROTACION', 'ESTRATEGIA ROTACION'), ('APRENDIZ', 'APRENDIZ'), ('NO PLUS', 'NO PLUS'), ('PTE RECUPERAR', 'PTE RECUPERAR'), ('MATERNIDAD', 'MATERNIDAD')], max_length=255, null=True),
        ),
    ]
