# Generated by Django 4.1 on 2026-03-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0017_contratos_personal_tipo_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos_personal',
            name='ciudad_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_ciudad_laboral', to='human_resources.ciudad'),
        ),
    ]
