# Generated by Django 4.1 on 2026-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0018_contratos_personal_ciudad_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='tap',
            field=models.CharField(blank=True, choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipo_posicion',
            field=models.CharField(choices=[('HC', 'HC'), ('HC PLUS', 'HC PLUS'), ('ESTRATEGIA ROTACION', 'ESTRATEGIA ROTACION'), ('APRENDIZ', 'APRENDIZ'), ('NO PLUS', 'NO PLUS'), ('PTE RECUPERAR', 'PTE RECUPERAR'), ('MATERNIDAD', 'MATERNIDAD')], default='HC', max_length=50),
        ),
    ]
