# Generated by Django 4.1 on 2026-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0019_cargo_tap_cargo_tipo_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personal',
            name='tipo_riesgo',
            field=models.CharField(choices=[('0', '0'), ('0.522', '0.522'), ('1.044', '1.044'), ('4.35', '4.35'), ('NO APLICA', 'NO APLICA'), ('OTRO', 'OTRO')], max_length=255),
        ),
    ]
