# Generated by Django 4.1 on 2023-04-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centro_costo',
            fields=[
                ('ceco', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=255)),
                ('cedo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuentas_contables',
            fields=[
                ('cuenta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=255)),
                ('nombre_cuenta_mayor', models.CharField(max_length=255)),
                ('subcuenta', models.CharField(max_length=255)),
            ],
        ),
    ]
