# Generated by Django 4.1 on 2023-04-16 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_cuentas_contables_nombre_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_r_p', models.CharField(blank=True, max_length=255, null=True)),
                ('nit_tercero', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_tercero', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='centro_costo',
            name='tipo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_tercero', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_tercero', models.CharField(blank=True, max_length=255, null=True)),
                ('importe', models.FloatField()),
                ('fecha', models.DateField()),
                ('n_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('importe_usd', models.FloatField(blank=True, null=True)),
                ('cebe', models.CharField(blank=True, max_length=255, null=True)),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
                ('asignacion', models.CharField(blank=True, max_length=255, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('ceco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.centro_costo')),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.clasificacion')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.cuentas_contables')),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_carga', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cierra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.centro_costo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.cuentas_contables'),
        ),
        migrations.CreateModel(
            name='rollling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('valor', models.FloatField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.clasificacion')),
            ],
            options={
                'unique_together': {('mes', 'anio', 'clasificacion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='clasificacion',
            unique_together={('tipo', 'tipo_r_p', 'cuenta', 'centro_costo', 'nit_tercero', 'responsable')},
        ),
    ]
