# Generated by Django 4.1 on 2023-04-16 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_clasificacion_centro_costo_tipo_gastos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='usuario_cierra',
        ),
        migrations.CreateModel(
            name='cierre_de_mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=255)),
                ('usuario_cierra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cierra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mes', 'anio', 'estado')},
            },
        ),
    ]
