# Generated by Django 4.1 on 2023-04-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_gastos_usuario_cierra_cierre_de_mes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cierre_de_mes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='cerrado',
        ),
        migrations.AddField(
            model_name='cierre_de_mes',
            name='annio',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cierre_de_mes',
            unique_together={('mes', 'annio', 'estado')},
        ),
        migrations.RemoveField(
            model_name='cierre_de_mes',
            name='anio',
        ),
    ]
