# Generated by Django 4.1 on 2023-04-17 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_alter_cierre_de_mes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_de_mes',
            name='usuario_cierra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_cierra', to=settings.AUTH_USER_MODEL),
        ),
    ]
