# Generated by Django 4.1 on 2023-04-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_cierre_de_mes_usuario_cierra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
