# Generated by Django 4.1 on 2023-04-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_clasificacion_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='posicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gastos',
            unique_together={('n_doc', 'posicion')},
        ),
    ]
