# Generated by Django 4.1 on 2023-04-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_gastos_posicion_alter_gastos_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cierre_de_mes',
            unique_together={('mes', 'annio')},
        ),
    ]
