# Generated by Django 4.1 on 2023-06-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
