# Generated by Django 4.1 on 2023-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_rules_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Clasificacion', 'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIJO', 'FIJO'), ('VARIABLE', 'VARIABLE'), ('MIXTO', 'MIXTO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='tipo_r_p',
            field=models.CharField(blank=True, choices=[('REAL', 'REAL'), ('PPTO', 'PPTO')], max_length=255, null=True, verbose_name='Real/Ppto'),
        ),
    ]
