# Generated by Django 4.1 on 2023-08-24 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0013_alter_centro_costo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='areas_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=255, unique=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
