# Generated by Django 4.1 on 2023-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_clasificacion_responsable_areas_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_de_mes',
            name='annio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='rollling',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
