# Generated by Django 4.1 on 2023-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_cierre_de_mes_annio_alter_rollling_anio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas_empresa',
            options={'verbose_name': 'Area empresa', 'verbose_name_plural': 'Areas empresa'},
        ),
        migrations.RemoveField(
            model_name='areas_empresa',
            name='id',
        ),
        migrations.AddField(
            model_name='rollling',
            name='valor_previo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areas_empresa',
            name='nombre_area',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('CALIDAD', 'CALIDAD'), ('CARTERA', 'CARTERA'), ('CEDI CARTAGENA', 'CEDI CARTAGENA'), ('CEDI MEDELLIN', 'CEDI MEDELLIN'), ('COMPRAS', 'COMPRAS'), ('CONS FINAL', 'CONS FINAL'), ('CONTABILIDAD', 'CONTABILIDAD'), ('CONTROL GESTION', 'CONTROL GESTION'), ('CRM', 'CRM'), ('GESTION HUMANA', 'GESTION HUMANA'), ('IMPORTACIONES', 'IMPORTACIONES'), ('IMPUESTOS', 'IMPUESTOS'), ('LOGISTICA BARRANQUILLA ', 'LOGISTICA BARRANQUILLA '), ('LOGISTICA BOGOTA', 'LOGISTICA BOGOTA'), ('LOGISTICA BUCARAMANGA', 'LOGISTICA BUCARAMANGA'), ('LOGISTICA CALI', 'LOGISTICA CALI'), ('LOGISTICA CARTAGENA', 'LOGISTICA CARTAGENA'), ('LOGISTICA CUCUTA', 'LOGISTICA CUCUTA'), ('LOGISTICA MEDELLIN', 'LOGISTICA MEDELLIN'), ('LOGISTICA PVA', 'LOGISTICA PVA'), ('MERCADEO', 'MERCADEO'), ('NO CONTROLABLE ', 'NO CONTROLABLE '), ('SIN ASIGNAR', 'SIN ASIGNAR'), ('TI', 'TI'), ('TRANSPORTES', 'TRANSPORTES'), ('VARIABLE', 'VARIABLE')], max_length=255, null=True),
        ),
    ]
