# Generated by Django 4.1 on 2024-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_areas_empresa_options_remove_areas_empresa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_contables',
            name='p_y_g',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
