# Generated by Django 4.1 on 2024-07-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_cuentas_contables_p_y_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B')], max_length=255, null=True),
        ),
    ]
