# Generated by Django 4.1 on 2024-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_alter_clasificacion_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='centro_costo',
            field=models.CharField(blank=True, choices=[('111000', '111000'), ('111001', '111001'), ('111003', '111003'), ('111100', '111100'), ('111200', '111200'), ('111300', '111300'), ('111400', '111400'), ('111500', '111500'), ('111700', '111700'), ('112000', '112000'), ('112001', '112001'), ('112004', '112004'), ('112005', '112005'), ('112090', '112090'), ('112100', '112100'), ('112200', '112200'), ('112300', '112300'), ('112400', '112400'), ('112500', '112500'), ('112600', '112600'), ('112700', '112700'), ('112800', '112800'), ('200060', '200060'), ('300000', '300000'), ('300001', '300001'), ('300002', '300002'), ('300003', '300003'), ('300004', '300004'), ('300005', '300005'), ('300006', '300006'), ('300007', '300007'), ('300008', '300008'), ('300009', '300009'), ('300020', '300020'), ('300021', '300021'), ('300022', '300022'), ('300023', '300023'), ('300040', '300040'), ('300041', '300041'), ('300042', '300042'), ('300043', '300043'), ('300044', '300044'), ('300045', '300045'), ('300046', '300046'), ('300060', '300060'), ('300080', '300080'), ('300081', '300081'), ('300082', '300082'), ('300100', '300100'), ('300120', '300120'), ('300140', '300140'), ('300160', '300160'), ('300180', '300180'), ('300181', '300181'), ('300182', '300182'), ('300200', '300200'), ('300201', '300201'), ('300220', '300220'), ('300240', '300240'), ('300260', '300260'), ('300261', '300261'), ('300280', '300280'), ('300300', '300300'), ('300320', '300320'), ('300321', '300321'), ('300322', '300322'), ('300323', '300323'), ('300340', '300340'), ('300341', '300341'), ('300360', '300360'), ('300380', '300380'), ('300400', '300400'), ('300420', '300420'), ('300440', '300440'), ('300460', '300460'), ('300480', '300480'), ('300500', '300500'), ('300501', '300501'), ('300502', '300502'), ('300503', '300503'), ('300504', '300504'), ('300505', '300505'), ('300506', '300506'), ('300507', '300507'), ('300508', '300508'), ('300520', '300520'), ('300700', '300700'), ('300701', '300701'), ('304000', '304000'), ('B2B', 'B2B'), ('CONS FINAL', 'CONS FINAL'), ('MERCADEO', 'MERCADEO'), ('PROYECTO CARTAGENA', 'PROYECTO CARTAGENA'), ('SEDE VIEJA MEDELLIN', 'SEDE VIEJA MEDELLIN'), (None, None)], max_length=255, null=True, verbose_name='Ceco/Orden'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('CALIDAD', 'CALIDAD'), ('CARTERA', 'CARTERA'), ('CEDI CARTAGENA', 'CEDI CARTAGENA'), ('CEDI MEDELLIN', 'CEDI MEDELLIN'), ('COMPRAS', 'COMPRAS'), ('CONS FINAL', 'CONS FINAL'), ('CONTABILIDAD', 'CONTABILIDAD'), ('CONTROL GESTION', 'CONTROL GESTION'), ('CRM', 'CRM'), ('GESTION HUMANA', 'GESTION HUMANA'), ('IMPORTACIONES', 'IMPORTACIONES'), ('IMPUESTOS', 'IMPUESTOS'), ('LOGISTICA BARRANQUILLA ', 'LOGISTICA BARRANQUILLA '), ('LOGISTICA BOGOTA', 'LOGISTICA BOGOTA'), ('LOGISTICA BUCARAMANGA', 'LOGISTICA BUCARAMANGA'), ('LOGISTICA CALI', 'LOGISTICA CALI'), ('LOGISTICA CARTAGENA', 'LOGISTICA CARTAGENA'), ('LOGISTICA CUCUTA', 'LOGISTICA CUCUTA'), ('LOGISTICA MEDELLIN', 'LOGISTICA MEDELLIN'), ('LOGISTICA PVA', 'LOGISTICA PVA'), ('MERCADEO', 'MERCADEO'), ('NO CONTROLABLE ', 'NO CONTROLABLE '), ('SIN ASIGNAR', 'SIN ASIGNAR'), ('TI', 'TI'), ('TRANSPORTES', 'TRANSPORTES'), ('VARIABLE', 'VARIABLE'), ('RETAIL', 'RETAIL'), ('CUMPLIMIENTO', 'CUMPLIMIENTO')], max_length=255, null=True),
        ),
    ]
